services:
  stage0:
    image: pp-resnet56:latest
    network_mode: "host"
    ipc: "host"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CUDA_VISIBLE_DEVICES=0
      - MASTER_ADDR=127.0.0.1
      - MASTER_PORT=29500
      - WORLD_SIZE=3
      - NODE_RANK=0
      - MICROBATCHES=8
      - BATCH=256
    command: >
      bash -lc "
      torchrun --nnodes=3 --nproc-per-node=1
              --node-rank=0
              --master-addr=${MASTER_ADDR}
              --master-port=${MASTER_PORT}
              /app/partition_resnet56
              .py"

  stage1:
    image: pp-resnet56:latest
    network_mode: "host"
    ipc: "host"
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
      - CUDA_VISIBLE_DEVICES=1
      - MASTER_ADDR=127.0.0.1
      - MASTER_PORT=29500
      - WORLD_SIZE=3
      - NODE_RANK=1
      - MICROBATCHES=8
      - BATCH=256
    command: >
      bash -lc "
      torchrun --nnodes=3 --nproc-per-node=1
              --node-rank=1
              --master-addr=${MASTER_ADDR}
              --master-port=${MASTER_PORT}
              /app/partition_resnet56.py"

  stage2:
    image: pp-resnet56:latest
    network_mode: "host"
    ipc: "host"
    environment:
      - NVIDIA_VISIBLE_DEVICES=2
      - CUDA_VISIBLE_DEVICES=2
      - MASTER_ADDR=127.0.0.1
      - MASTER_PORT=29500
      - WORLD_SIZE=3
      - NODE_RANK=2
      - MICROBATCHES=8
      - BATCH=256
    command: >
      bash -lc "
      torchrun --nnodes=3 --nproc-per-node=1
              --node-rank=2
              --master-addr=${MASTER_ADDR}
              --master-port=${MASTER_PORT}
              /app/partition_resnet56.py"
