---
apiVersion: v1
kind: Pod
metadata:
  name: partition_1
spec:
  containers:
  - name: partition_1
    image: 
    ports:
    - partition_2_PORT: 8001
  resources:
    requests:
    - memory: "4Gi"
      cpu: "1"
    limits:
    - memory: "4Gi"
      cpu: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: partition_2
spec:
  containers:
  - name: partition_2
    image: 
    ports:
    - containerPort: 8001
      partition_3_PORT: 8002
  resources:
    requests:
    - memory: "4Gi"
      cpu: "1"
    limits:
    - memory: "4Gi"
      cpu: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: partition_3
spec:
  containers:
  - name: partition_3
    image: 
    ports:
    - containerPort: 8002
      partition_3_PORT: 8003
  resources:
    requests:
    - memory: "4Gi"
      cpu: "1"
    limits:
    - memory: "4Gi"
      cpu: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: partition_4
spec:
  containers:
  - name: partition_4
    image: 
    ports:
    - containerPort: 8003
  resources:
    requests:
    - memory: "4Gi"
      cpu: "1"
    limits:
    - memory: "4Gi"
      cpu: "1"